Repository Hi-Folks/statistics, pull requests merged in 2023-10, with the labels that each got.

#37 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#40 including Pint in all-check script
  composer.json
Labels: hacktoberfest

#41 uses: actions/checkout@v4
  .github/workflows/run-tests.yml
  .github/workflows/static-code-analysis.yml
Labels: hacktoberfest, hacktoberfest-accepted

#42 Enhanced Contribution guidelines
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted

#43 Enhanced the presentation and language of the README
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#44 Enhanced presentation and description of the readme
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#46 Enhanced the CODE_OF_CONDUCT Guidelines
  CODE_OF_CONDUCT.md
Labels: hacktoberfest, hacktoberfest-accepted

#45 Enhanced the presentation of the README.md file
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#48 Enhanced the description of statistic functions
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#49 Enhanced the Security Policies
  .github/SECURITY.md
Labels: hacktoberfest, hacktoberfest-accepted

#50 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#51 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest, hacktoberfest-accepted

#52 Enhanced and Improved the SECURITY.md file
  .github/SECURITY.md
Labels: hacktoberfest, hacktoberfest-accepted

#56 Update phpstan.neon - level 8
  phpstan.neon
Labels: hacktoberfest, hacktoberfest-accepted

#57 Update Rector configuration UP_TO_PHP_81
  rector.php
Labels: hacktoberfest, hacktoberfest-accepted

#58 refactoring with Rector
  composer.json
  rector.php
  src/ArrUtil.php
  src/Freq.php
  src/Stat.php
  src/Statistics.php
Labels: hacktoberfest, hacktoberfest-accepted

#63 Update README.md
  README.md
Labels: hacktoberfest-accepted
